// ALERTS
export const SHOW_ALERT = "SHOW_ALERT";
export const HIDE_ALERT = "HIDE_ALERT";

// FETCH DELIVERIES
export const FETCH_DELIVERIES_REQUEST = "FETCH_DELIVERIES_REQUEST";
export const FETCH_DELIVERIES_SUCCESS = "FETCH_DELIVERIES_SUCCESS";
export const FETCH_DELIVERIES_FAILURE = "FETCH_DELIVERIES_FAILURE";
 


//Finish Delivery  
export const FINISH_DELIVERY_REQUEST = "FINISH_DELIVERY_REQUEST";
export const FINISH_DELIVERY_SUCCESS = "FINISH_DELIVERY_SUCCESS";
export const FINISH_DELIVERY_FAILURE = "FINISH_DELIVERY_FAILURE";
 

//Activate Delivery For UI
export const ACTIVATE_DELIVERY = "ACTIVATE_DELIVERY";
export const DEACTIVATE_DELIVERY = "DEACTIVATE_DELIVERY";

export const DELETE_FINISH_DELIVERY_STATUS = "DELETE_FINISH_DELIVERY_STATUS";
export const DELETE_ERROR_FINISH_DELIVERY = "DELETE_ERROR_FINISH_DELIVERY"; 


